layout_spectrum: 0.22824922646395862
typography_spectrum: 0.28616087953560054
color:
  brandColors:
    - '#E6E2AF'
    - '#A7A37E'
    - '#EFECCA'
    - '#046380'
    - '#002F2F'
  brandStrength: 0.31251724204048514
  lightness: 0.7288436251692474
  saturation: 0.00012221257202327251
  rhythmicContrast: 0.40145791810937226
coverPrefs:
  filter: false
name: UBG - Uber Business Group
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/901ce121-f96f-4015-aefe-97972b3235f9.png
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/f70a7a5c-cc41-43e3-be52-3b80a871b3c1.png
opengraph:
  type: ''
  appId: ''
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/844619a8-b112-4dee-b2c3-d927dc551d34.png
title: ubg
author:
  name: ''
  url: ''
  email: ''
content_rating:
  adult: false
